table UnPivot1
	lineageTag: 9450bafc-8344-4e4d-be4c-e293af8db201

	column 'Content Area'
		dataType: string
		lineageTag: d2964d8b-f6e4-4f53-bc03-c0dc29927bbe
		summarizeBy: none
		sourceColumn: Content Area

		annotation SummarizationSetBy = Automatic

	column Grade
		dataType: int64
		formatString: 0
		lineageTag: 0aea158d-5325-4d48-bc4a-7248d0353b9c
		summarizeBy: sum
		sourceColumn: Grade

		annotation SummarizationSetBy = Automatic

	column 'Assessment Name'
		dataType: string
		lineageTag: 68364daa-3bed-4b08-ba1a-872596e1847c
		summarizeBy: none
		sourceColumn: Assessment Name

		annotation SummarizationSetBy = Automatic

	column 'DRC INSIGHT Test Name'
		dataType: string
		lineageTag: 92c46a37-bdb5-4d04-bc65-ba752e820d4b
		summarizeBy: none
		sourceColumn: DRC INSIGHT Test Name

		annotation SummarizationSetBy = Automatic

	column 'Assessment Number'
		dataType: int64
		formatString: 0
		lineageTag: 36c41219-ee8b-491a-b53d-a472082d9bd9
		summarizeBy: sum
		sourceColumn: Assessment Number

		annotation SummarizationSetBy = Automatic

	column PAsecureID
		dataType: int64
		formatString: 0
		lineageTag: 5aa5c325-4a99-4d9d-b005-b4158e1850fd
		summarizeBy: none
		sourceColumn: PAsecureID

		annotation SummarizationSetBy = Automatic

	column 'Test Session Name'
		dataType: string
		lineageTag: 65b32802-d059-42de-9dca-2a68a08dcf05
		summarizeBy: none
		sourceColumn: Test Session Name

		annotation SummarizationSetBy = Automatic

	column AHCCSsession
		dataType: string
		lineageTag: cecdde1b-3328-435d-879d-295de088ac06
		summarizeBy: none
		sourceColumn: AHCCSsession

		annotation SummarizationSetBy = Automatic

	column Teacher
		dataType: string
		lineageTag: 10ae0ab4-c7ae-4dda-b3b9-227650e61346
		summarizeBy: none
		sourceColumn: Teacher

		annotation SummarizationSetBy = Automatic

	column CKBatchAssmtnameGrade
		dataType: string
		lineageTag: bc8576a5-04d8-4d14-a94d-2d15d01932df
		summarizeBy: none
		sourceColumn: CKBatchAssmtnameGrade

		annotation SummarizationSetBy = Automatic

	column 'Measure Type'
		dataType: string
		lineageTag: b61e88ae-8fe4-4772-bb95-ee3a1ccba9d9
		summarizeBy: none
		sourceColumn: Measure Type

		annotation SummarizationSetBy = Automatic

	column 'Score Category'
		dataType: string
		lineageTag: 7ee89bdd-89b0-48ff-ab08-c610b9c4602c
		summarizeBy: none
		sourceColumn: Score Category

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: int64
		formatString: 0
		lineageTag: 6150621b-52c4-4896-8392-859492790349
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition UnPivot1 = m
		mode: import
		source =
				let
				    Source = BatchDownload,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Content Area", "Grade", "Assessment Name", "DRC INSIGHT Test Name", "Assessment Number", "PAsecureID", "Test Session Name", "Scale Score for DC 1", "Scale Score for DC 2", "Scale Score for DC 3", "Scale Score for DC 4", "Scale Score for DC 5", "Total Scale Score for Test", "SEM Upper for Total Scale Score", "SEM Upper for DC 1 Scale Score", "SEM Upper for DC 2 Scale Score", "SEM Upper for DC 3 Scale Score", "SEM Upper for DC 4 Scale Score", "SEM Upper for DC 5 Scale Score", "SEM Lower for Total Scale Score", "SEM Lower for DC 1 Scale Score", "SEM Lower for DC 2 Scale Score", "SEM Lower for DC 3 Scale Score", "SEM Lower for DC 4 Scale Score", "SEM Lower for DC 5 Scale Score", "AHCCSsession", "Teacher", "CKBatchAssmtnameGrade"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"Scale Score for DC 1", "Scale DC1"}, {"Scale Score for DC 2", "Scale DC2"}, {"Scale Score for DC 3", "Scale DC3"}, {"Scale Score for DC 4", "Scale DC4"}, {"Scale Score for DC 5", "Scale DC5"}, {"Total Scale Score for Test", "Scale Total"}, {"SEM Upper for Total Scale Score", "SEM Upper Total"}, {"SEM Lower for Total Scale Score", "SEM Lower Total"}, {"SEM Upper for DC 1 Scale Score", "SEM Upper DC1"}, {"SEM Upper for DC 2 Scale Score", "SEM Upper DC2"}, {"SEM Upper for DC 3 Scale Score", "SEM Upper DC3"}, {"SEM Upper for DC 4 Scale Score", "SEM Upper DC4"}, {"SEM Upper for DC 5 Scale Score", "SEM Upper DC5"}, {"SEM Lower for DC 1 Scale Score", "SEM Lower DC1"}, {"SEM Lower for DC 2 Scale Score", "SEM Lower DC2"}, {"SEM Lower for DC 3 Scale Score", "SEM Lower DC3"}, {"SEM Lower for DC 4 Scale Score", "SEM Lower DC4"}, {"SEM Lower for DC 5 Scale Score", "SEM Lower DC5"}}),
				    #"Unpivoted Only Selected Columns" = Table.Unpivot(#"Renamed Columns", {"Scale DC1", "Scale DC2", "Scale DC3", "Scale DC4", "Scale DC5", "Scale Total", "SEM Upper Total", "SEM Upper DC1", "SEM Upper DC2", "SEM Upper DC3", "SEM Upper DC4", "SEM Upper DC5", "SEM Lower Total", "SEM Lower DC1", "SEM Lower DC2", "SEM Lower DC3", "SEM Lower DC4", "SEM Lower DC5"}, "Attribute", "Value"),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Unpivoted Only Selected Columns", "Attribute", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, true), {"Attribute.1", "Attribute.2"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Split Column by Delimiter",{{"Attribute.1", "Measure Type"}, {"Attribute.2", "Score Category"}})
				in
				    #"Renamed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

